

# NOTE: This file is generated by m4! Make sure you're editing the .m4 version,
# not the generated version!

# 3.5.0
LIBAOM_VERSION=bcfe6fbf

tmp-inst/%/lib/pkgconfig/aom.pc: libaom-$(LIBAOM_VERSION)/build-%/Makefile
	cd libaom-$(LIBAOM_VERSION)/build-$* ; \
		$(MAKE) install

# General build rule for any target
# Use: buildrule(target name, cmake flags)


# Non-threaded

libaom-$(LIBAOM_VERSION)/build-base/Makefile: tmp-inst/base/cflags.txt libaom-$(LIBAOM_VERSION)/PATCHED
	mkdir -p libaom-$(LIBAOM_VERSION)/build-base
	cd libaom-$(LIBAOM_VERSION)/build-base ; \
		emcmake cmake .. -DCMAKE_INSTALL_PREFIX="$(PWD)/tmp-inst/base" \
		-DCMAKE_C_FLAGS="-Oz `cat $(PWD)/tmp-inst/base/cflags.txt`" \
		-DCMAKE_CXX_FLAGS="-Oz `cat $(PWD)/tmp-inst/base/cflags.txt`" \
		-DAOM_TARGET_CPU=generic \
		-DCMAKE_BUILD_TYPE=Release \
		-DENABLE_DOCS=0 \
		-DENABLE_TESTS=0 \
		-DENABLE_EXAMPLES=0 \
		-DCONFIG_RUNTIME_CPU_DETECT=0 \
		-DCONFIG_WEBM_IO=0 \
                -DCONFIG_MULTITHREAD=0
	touch $(@)


libaom-$(LIBAOM_VERSION)/build-simd/Makefile: tmp-inst/simd/cflags.txt libaom-$(LIBAOM_VERSION)/PATCHED
	mkdir -p libaom-$(LIBAOM_VERSION)/build-simd
	cd libaom-$(LIBAOM_VERSION)/build-simd ; \
		emcmake cmake .. -DCMAKE_INSTALL_PREFIX="$(PWD)/tmp-inst/simd" \
		-DCMAKE_C_FLAGS="-Oz `cat $(PWD)/tmp-inst/simd/cflags.txt`" \
		-DCMAKE_CXX_FLAGS="-Oz `cat $(PWD)/tmp-inst/simd/cflags.txt`" \
		-DAOM_TARGET_CPU=generic \
		-DCMAKE_BUILD_TYPE=Release \
		-DENABLE_DOCS=0 \
		-DENABLE_TESTS=0 \
		-DENABLE_EXAMPLES=0 \
		-DCONFIG_RUNTIME_CPU_DETECT=0 \
		-DCONFIG_WEBM_IO=0 \
                -DCONFIG_MULTITHREAD=0
	touch $(@)

# Threaded

libaom-$(LIBAOM_VERSION)/build-thr/Makefile: tmp-inst/thr/cflags.txt libaom-$(LIBAOM_VERSION)/PATCHED
	mkdir -p libaom-$(LIBAOM_VERSION)/build-thr
	cd libaom-$(LIBAOM_VERSION)/build-thr ; \
		emcmake cmake .. -DCMAKE_INSTALL_PREFIX="$(PWD)/tmp-inst/thr" \
		-DCMAKE_C_FLAGS="-Oz `cat $(PWD)/tmp-inst/thr/cflags.txt`" \
		-DCMAKE_CXX_FLAGS="-Oz `cat $(PWD)/tmp-inst/thr/cflags.txt`" \
		-DAOM_TARGET_CPU=generic \
		-DCMAKE_BUILD_TYPE=Release \
		-DENABLE_DOCS=0 \
		-DENABLE_TESTS=0 \
		-DENABLE_EXAMPLES=0 \
		-DCONFIG_RUNTIME_CPU_DETECT=0 \
		-DCONFIG_WEBM_IO=0 \
                
	touch $(@)


libaom-$(LIBAOM_VERSION)/build-thrsimd/Makefile: tmp-inst/thrsimd/cflags.txt libaom-$(LIBAOM_VERSION)/PATCHED
	mkdir -p libaom-$(LIBAOM_VERSION)/build-thrsimd
	cd libaom-$(LIBAOM_VERSION)/build-thrsimd ; \
		emcmake cmake .. -DCMAKE_INSTALL_PREFIX="$(PWD)/tmp-inst/thrsimd" \
		-DCMAKE_C_FLAGS="-Oz `cat $(PWD)/tmp-inst/thrsimd/cflags.txt`" \
		-DCMAKE_CXX_FLAGS="-Oz `cat $(PWD)/tmp-inst/thrsimd/cflags.txt`" \
		-DAOM_TARGET_CPU=generic \
		-DCMAKE_BUILD_TYPE=Release \
		-DENABLE_DOCS=0 \
		-DENABLE_TESTS=0 \
		-DENABLE_EXAMPLES=0 \
		-DCONFIG_RUNTIME_CPU_DETECT=0 \
		-DCONFIG_WEBM_IO=0 \
                
	touch $(@)


extract: libaom-$(LIBAOM_VERSION)/PATCHED

libaom-$(LIBAOM_VERSION)/PATCHED: libaom-$(LIBAOM_VERSION)/CMakeLists.txt
	cd libaom-$(LIBAOM_VERSION) ; test -e PATCHED || patch -p1 -i ../patches/libaom.diff
	touch $@

libaom-$(LIBAOM_VERSION)/CMakeLists.txt: libaom-$(LIBAOM_VERSION).tar.gz
	mkdir -p libaom-$(LIBAOM_VERSION)
	cd libaom-$(LIBAOM_VERSION) ; \
		tar zxf ../libaom-$(LIBAOM_VERSION).tar.gz
	touch $@

libaom-$(LIBAOM_VERSION).tar.gz:
	curl https://aomedia.googlesource.com/aom/+archive/$(LIBAOM_VERSION).tar.gz -L -o $@

libaom-release:
	cp libaom-$(LIBAOM_VERSION).tar.gz libav.js-$(LIBAVJS_VERSION)/sources/

.PRECIOUS: \
	tmp-inst/%/lib/pkgconfig/aom.pc \
	libaom-$(LIBAOM_VERSION)/build-%/Makefile \
	libaom-$(LIBAOM_VERSION)/PATCHED \
	libaom-$(LIBAOM_VERSION)/CMakeLists.txt
