build/ffmpeg-$(FFMPEG_VERSION)/build-base-open-media/ffbuild/config.mak: build/inst/base/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-open-media/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-open-media/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-open-media/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-open-media/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-open-media/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-open-media/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-open-media/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-open-media/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-open-media/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-open-media/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-open-media/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-open-media/ffbuild/config.mak: build/inst/base/lib/pkgconfig/aom.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-open-media/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/aom.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-open-media/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/aom.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-open-media/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/aom.pc
