build/ffmpeg-$(FFMPEG_VERSION)/build-base-obsolete/ffbuild/config.mak: build/inst/base/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-obsolete/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-obsolete/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-obsolete/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-obsolete/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-obsolete/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-obsolete/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-obsolete/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-obsolete/ffbuild/config.mak: build/inst/base/lib/libmp3lame.a
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-obsolete/ffbuild/config.mak: build/inst/simd/lib/libmp3lame.a
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-obsolete/ffbuild/config.mak: build/inst/thr/lib/libmp3lame.a
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-obsolete/ffbuild/config.mak: build/inst/thrsimd/lib/libmp3lame.a
