build/ffmpeg-$(FFMPEG_VERSION)/build-base-mediarecorder-openh264/ffbuild/config.mak: build/inst/base/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-mediarecorder-openh264/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-mediarecorder-openh264/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-mediarecorder-openh264/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-mediarecorder-openh264/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-mediarecorder-openh264/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-mediarecorder-openh264/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-mediarecorder-openh264/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-mediarecorder-openh264/ffbuild/config.mak: build/inst/base/lib/pkgconfig/openh264.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-simd-mediarecorder-openh264/ffbuild/config.mak: build/inst/simd/lib/pkgconfig/openh264.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-mediarecorder-openh264/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/openh264.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thrsimd-mediarecorder-openh264/ffbuild/config.mak: build/inst/thrsimd/lib/pkgconfig/openh264.pc
